waypoints: [8, 12,
            8, 13,
            7, 13,
            6, 13,
            5, 13,
            4, 13,
            3, 13,
            2, 13,
            2, 14,
            3, 14,
            4, 14,
            5, 14,
            6, 14,
            7, 14,
            7, 15,
            7, 16,
            7, 17,
            6, 17,
            5, 17,
            4, 17,
            3, 17,
            2, 17,
            2, 18,
            3, 18,
            4, 18,
            5, 18,
            6, 18,
            7, 18,
            7, 19,
            8, 19,
            8, 20,]